repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    - id: isort
      additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3
      args: [--line-length=100]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      additional_dependencies: [types-aiofiles]
      files: async_search_client/
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [flake8-print]
      args: ["--ignore=E203,E231,E501,D100,D101,D102,D103,D104,D105,D106,D107,D401"]
